[toolchain]
# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history/wasm32-unknown-unknown.html
channel = "nightly-2025-09-23"
targets = ["wasm32-unknown-unknown"]
components = ["rust-src", "rustfmt", "clippy"]
